-- DGSL Site Register TEST notifications
-- Run this in Supabase SQL Editor for the shared DGSL project.

create table if not exists public.site_notifications_test (
  id bigint generated by default as identity primary key,
  version text not null unique,
  title text not null default 'Website updated',
  message text not null,
  created_at timestamptz not null default now()
);

alter table public.site_notifications_test enable row level security;

create policy "Allow authenticated test notification read access"
on public.site_notifications_test
for select
to authenticated
using (true);

-- The GitHub Actions workflow uses the Supabase service-role key to insert
-- notifications after a successful TEST deployment. Service-role access
-- bypasses RLS, so no public/authenticated INSERT policy is required.
